name: 'Deploy ESK to AWS'
description: 'Deploy Kubernetes Service (EKS) to AWS'
branding:
  icon: upload-cloud
  color: red
inputs:
  # Checkout
  checkout:
    description: 'Specifies if this action should checkout the code'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout if required'
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

    - name: Install Terraform
      shell: bash
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      shell: bash
      id: init
      working-directory: terraform
      run: terraform init

    - name: Terraform Validate
      shell: bash
      id: validate
      working-directory: terraform
      run: terraform validate -no-color  
          
    - name: Terraform Plan
      shell: bash
      id: plan
      working-directory: terraform
      run: terraform plan -no-color     

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}