name: 'Deploy ESK to AWS'
description: 'Deploy Kubernetes Service (EKS) to AWS'
branding:
  icon: upload-cloud
  color: red
inputs:
  # Checkout
  checkout:
    description: 'Specifies if this action should checkout the code'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout if required'
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

