helm:
  cli:
    namespace: cert-manager
    timeout: 500s
    debug: true
    atomic: true
    force: false
    dry-run: false
  options:
    release-name: cert-manager
    skip-deploy: true
    kubeconfig:
      fetch:
        enabled: true
        cluster-name: recruiting-recruiting-recruiting-ekscluster

