prometheus:
  alertmanager:
    enabled: true
    persistentVolume:
      enabled: false

  configmapReload:
    prometheus:
      enabled: true
    alertmanager:
      enabled: true
  kubeStateMetrics:
    enabled: true

  ## kube-state-metrics sub-chart configurable values
  ## Please see https://github.com/kubernetes/kube-state-metrics/tree/master/charts/kube-state-metrics
  ##
  # kube-state-metrics:

  nodeExporter:
    enabled: true

  server:
    enabled: true
    global:
      ## How frequently to scrape targets by default
      ##
      scrape_interval: 1m
      ## How long until a scrape request times out
      ##
      scrape_timeout: 10s
      ## How frequently to evaluate rules
      ##
      evaluation_interval: 1m

    persistentVolume:
      enabled: false

    replicaCount: 1


    ingress:
      ## If true, Prometheus server Ingress will be created
      ##
      enabled: false

      ## Prometheus server Ingress annotations
      ##
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod

        # https://cert-manager.io/docs/faq/acme/#:~:text=If%20you%20receive%20a%20tls,the%20actual%20certificate%20is%20issued
        cert-manager.io/issue-temporary-certificate: "true"
        acme.cert-manager.io/http01-edit-in-place: "true"

      ## Prometheus server Ingress additional labels
      ##
      extraLabels: {}

      ## Prometheus server Ingress hostnames with optional path
      ## Must be provided if Ingress is enabled
      ##

      hosts:
      - prometheus.dev.bitovi-staffing.com

      ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
      extraPaths: []
      # - path: /*
      #   backend:
      #     serviceName: ssl-redirect
      #     servicePort: use-annotation

      ## Prometheus server Ingress TLS configuration
      ## Secrets must be manually created in the namespace
      ##
      tls:
        - secretName: prometheus-server-tls
          hosts:
            - prometheus.dev.bitovi-staffing.com

  pushgateway:
    enabled: false

  alertmanagerFiles:
    alertmanager.yml:
      global: {}
        # slack_api_url: ''

      receivers:
        - name: default-receiver
          # slack_configs:
          #  - channel: '@you'
          #    send_resolved: true

      route:
        group_wait: 10s
        group_interval: 5m
        receiver: default-receiver
        repeat_interval: 3h

  # adds additional scrape configs to prometheus.yml
  # must be a string so you have to add a | after extraScrapeConfigs:
  # example adds prometheus-blackbox-exporter scrape config
  # extraScrapeConfigs:
    # - job_name: 'prometheus-blackbox-exporter'
    #   metrics_path: /probe
    #   params:
    #     module: [http_2xx]
    #   static_configs:
    #     - targets:
    #       - https://example.com
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: prometheus-blackbox-exporter:9115
